palette = "evan"
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character
"""

[palettes.evan]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"
bright-black = "#928374"
bright-red = "#ea6962"
bright-green = "#a9b665"
bright-yellow = "#e3a84e"
bright-blue = "#7daea3"
bright-magenta = "#d3869b"
bright-cyan = "#89b482"
bright-white = "#dfbf8e"

[package]
disabled = true

[python]
symbol = "Python "

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "diverged ⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"
format = '([\[ ($ahead_behind )($staged )($modified )($untracked )($stashed )($renamed )($deleted )\]]($style) )'
